### PR TITLE
Add print and return args, fix #86

### LINKED ISSUE #86: Function that return options as string
Hi,
Thanks for this lib!
Could you please add a func that return all the nmap options/params passed to the scanner?
Regards,

### PR DESCRIPTION
**Pull request by cyrinux**
Hi @Ullaakut

This should add what I miss in the issue #86

Regards

### CODE REVIEW

**Comment by cyrinux** [comment]
Do you 

> I do not think that a package that is used as an nmap wrapper library should be able to print things. The `Args()` method is enough, and allows the consumer of the package to do `fmt.Println(scanner.Args())` if they want to.
> 
> Because of this, I would suggest removing this `PrintArgs` method altogether.

So should I return a string or an []string?

**Comment by Ullaakut** [comment]
@cyrinux It's better to return the `[]args` and let the consumer of the package decide how they want to print it :)

**Comment by cyrinux** [comment]
Ok so we are ok like this 😸

**Review by Ullaakut — APPROVED** [review]

**Comment by Ullaakut** [comment]
@cyrinux Indeed 😄 Thank you for your contribution! :)

**Comment by cyrinux** [comment]
Thanks you @Ullaakut !

**Comment by cyrinux** [comment]
Can you cut a release then 🙏🏻 ? I would like to got confidence fix and this one awesome fix 🥇

**Pull request merged**
