### PR TITLE
Added error type and enhanced the error checking

### PR DESCRIPTION
**Pull request by noneymous**
Pull request for #44

### CODE REVIEW

**Comment by Ullaakut** [comment]
Great work @noneymous, thanks! When I have some time I might add some cases in there to improve error handling :D 

In the meantime, this is already awesome 👍

**Comment by noneymous** [comment]
Thank's. I'll execute a quite large scan the next weeks, so I might come up with some more cases too...

**Comment by noneymous** [comment]
Just to let you know, after scanning hundreds of networks the last two weeks, I didn't run into additional error cases.

**Comment by Ullaakut** [comment]
Thanks for the update @noneymous :D

**Pull request merged**
